### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by ngx45** [arminlinder/Lazarus-FPC-Wiki-Code-Samples#1]
Hi Armin

Thanks for your great work.

Lazarus 2.2.0 (rev lazarus_2_2_0-98-gdf61f81b7d) FPC 3.2.3 i386-win32-win32/win64

I test code only.

On armbian (arm armv7 linux), it works.

But, on windows 10 Pro x64 , sometime workerthread execute method never executed. Attached command line log (libreoffice docx).

If I change Name or DisplayName or Description -> it won't work.

      Name := 'TestDaemonCodeOnly';            // Service name
      DisplayName := 'Test Daemon (CodeOnly)'; // Service display name
      Description := 'Lazarus Daemons and Services Wiki Demo Service (Created in Code only)';    

Regards,
ngx45

[cmd_prompt.docx](https://github.com/arminlinder/Lazarus-FPC-Wiki-Code-Samples/files/8203425/cmd_prompt.docx)

**Comment by arminlinder** [comment]
Wanted to send you a test program, but some security filter won't let me. Can you please contact me and send an E-Mail I can send to? Thnx, Armin.

**Comment by ngx45** [comment]
Hi, 

Gmail security filter is harder than github.  

You can attach exe file here in github, use below work around: 
1) exe file compress using 7z, use password=abc.            https://www.7-zip.org/
2) add .zip extension

[TestDaemonCodeOnly.7z.zip](https://github.com/arminlinder/Lazarus-FPC-Wiki-Code-Samples/files/8204700/TestDaemonCodeOnly.7z.zip)

Or, delete the exe file, attach only the source files, I can compile it

Thanks,

**Comment by arminlinder** [comment]
Tried to fool GMail using 7-Zip, but still the mail gets rejected: "This message was blocked because its content presents a potential security issue".

For your tests, I checked the Windows and Linux executables into GitHub, please load from there. If the exe runs, we need to look into your build environment.

Meanwhile I tested on Microsoft Windows [Version 10.0.19043.1526], no problem found, daemon installs and executes the worker like intended.

You could also consider to follow my instructions in the wiki on how to attach a debugger under Windows and see where the code strolls along.

And thanks for your feedback concerning armbian!

Armin.

**Comment by ngx45** [comment]
Hi Armin,

It didnt work because I put the all project files in OneDrive shared folder.

All works now.

Btw in DaemonUnit1.pas line 115, there is a param mismatch 

  LogToFile(Format('Daemon %s received start signal, PID:%d', [GetProcessID]));  


Thanks.

**Comment by arminlinder** [comment]
Thanks for your valuable infos.

I added a note to the wiki to be careful when trying to access virtual drives from a service acocunt, and corrected the glitch in the Format statement. Happy coding!
